_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_5shot_combine/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 39
    OUTPUT_LAYER: "CosineSimOutputLayers"
  #   FREEZE_FEAT: False
  BACKBONE:
    FREEZE: True
  # PROPOSAL_GENERATOR:
  #   FREEZE: False
DATASETS:
  TRAIN: ('coco_gdt_trainval_all_6shot',)
  TEST: ('coco_gdt_test',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.1
  STEPS: (500,)
  MAX_ITER: 9000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_6shot_gdt"