[project]
name = "gdt-few-shot-symbol-detection"
description = "Few-Shot Object Detection (FsDet) setup with CPU/GPU envs"
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64"]

[tasks]
# Install Detectron2 matching torch/cuda for CPU
install-d2-cpu = "python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.10/index.html"
# Install Detectron2 for CUDA 10.2 with torch1.9/1.10 as needed
install-d2-cu102 = "python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.10/index.html"
# Install Detectron2 for CUDA 11.1
install-d2-cu111 = "python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.10/index.html"
# Install Detectron2 for CUDA 11.3
install-d2-cu113 = "python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html"
# Fallback: build from source (ensure gcc/g++>=5.4)
install-d2-source = "python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'"
# Add libg11
install-libg11 = "sudo apt-get install libgl1-mesa-glx"

[feature.main.dependencies]
python = ">=3.8,<3.12"
numpy = "*"
tqdm = "*"
matplotlib = "*"
termcolor = "*"
yacs = "*"
tabulate = "*"
cloudpickle = "*"
pillow = "*"
imagesize = "*"
tensorboard = ">=2.0.0"
pycocotools = "*"
fvcore = "*"
iopath = "*"
pip = "*"

[feature.cpu.dependencies]
pytorch = "1.10.*"
torchvision = "0.11.*"
cpuonly = "*"

[feature.gpu.system-requirements]
cuda = "11.3"

[feature.gpu.dependencies]
pytorch = "1.10.*"
torchvision = "0.11.*"
cudatoolkit = "11.3.*"

[pypi-dependencies]
lvis = "*"
opencv-contrib-python-headless = "*"

[environments]
cpu = { features = ["main", "cpu"] }
gpu = { features = ["main", "gpu"] }

[feature.dev.dependencies]
pre-commit = "*"

[environments.dev]
features = ["main", "cpu", "dev"]

[dependencies]
python = ">=3.8,<3.12"
