[project]
name = "gdt-few-shot-symbol-detection"
description = "Few-Shot Object Detection (FsDet) setup with CPU/GPU envs"
channels = ["conda-forge"]
platforms = ["linux-64"]

[activation]
env = { LD_LIBRARY_PATH = "${PIXI_PROJECT_ROOT}/.pixi/envs/main/lib:${LD_LIBRARY_PATH}" }

[tasks]
install-torch = "python -m pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html"
install-d2 = "python -m pip install detectron2==0.4 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.8/index.html"

[feature.main.dependencies]
python = ">=3.8,<3.10"
numpy = "<2.0.0"
tqdm = "*"
matplotlib = "*"
termcolor = "*"
yacs = "*"
tabulate = "*"
cloudpickle = "*"
pillow = "<9.0.0"
imagesize = "*"
tensorboard = ">=2.0.0"
pycocotools = "*"
fvcore = "*"
iopath = "*"
pip = "*"

[pypi-dependencies]
lvis = "*"
opencv-python-headless = "*"

[environments]
main = { features = ["main"] }

[feature.dev.dependencies]
pre-commit = "*"

[dependencies]
python = ">=3.8,<3.10"
